### ISSUE TITLE
Documentation, Preloading, Thread-Safety

### ISSUE THREAD

**Issue by yfeldblum** [asaaki/ryodo#4]
In the interest of thread-safety, multithreaded applications should preload the suffix-list and the rule-set.

```
# Preload the Ryodo Public Suffix List and Parser
Ryodo::SuffixList.instance
Ryodo::Parser.instance

# And the rest of application startup....
# Make some threads or child processes....
# Work work work....
```

This requirement should be _documented_ in the readme file.

There should also be a convenient method to preload both of these things: `Ryodo.preload` or something like that.

**Comment by asaaki** [comment]
No active development.
